import "./globals.css";
import TopHeader from "./components/TopHeader";
import MainHeader from "./components/MainHeader";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        <MainHeader />
        {children}  
        <Footer />
      </body>
    </html>
  );
}
